In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
basketball_awards_players = pd.read_csv('data/basketball_awards_players.csv', ',')
basketball_coaches = pd.read_csv('data/basketball_coaches.csv', ',')
basketball_draft = pd.read_csv('data/basketball_draft.csv', ',')

basketball_hof = pd.read_csv('data/basketball_hof.csv', ',')
basketball_master = pd.read_csv('data/basketball_master.csv', ',')
basketball_player_allstar = pd.read_csv('data/basketball_player_allstar.csv', ',')
basketball_players = pd.read_csv('data/basketball_players (2).csv', ',')
basketball_players2 = pd.read_csv('data/basketball_players.csv', ',')
basketball_series_post = pd.read_csv('data/basketball_series_post.csv', ',')

basketball_teams = pd.read_csv('data/basketball_teams.csv', ',')
nbaallelo = pd.read_csv('data/nbaallelo.csv', ',')
ncaa_team_data = pd.read_csv('data/ncaa-team-data.csv', ',')
Players = pd.read_csv('data/Players.csv', ',')
Seasons_Stats = pd.read_csv('data/Seasons_Stats.csv', ',')

salaries = pd.read_csv('nba_salaries_1990_to_2018.csv', ',')
salaries1978 = pd.read_csv('data/jgrosz99-nba-player-data-1978-2016/data/nba_season_data.csv', ',')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (18,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
all_columns = []

column_list = (basketball_awards_players.columns.tolist(),
basketball_coaches.columns.tolist(),
basketball_draft.columns.tolist(),
basketball_hof.columns.tolist(),
basketball_master.columns.tolist(),
basketball_player_allstar.columns.tolist(),
basketball_players.columns.tolist(),
basketball_series_post.columns.tolist(),
basketball_teams.columns.tolist(),
nbaallelo.columns.tolist(),
ncaa_team_data.columns.tolist(),
Players.columns.tolist(),
Seasons_Stats.columns.tolist())

for cols in column_list:
    for item in cols:
        item = item.lower()
        if not item in all_columns:
            all_columns += [item]

In [8]:
# basketball_abbrev
# basketball_awards_coaches 
##year, coachID, lgID


total_list = []

total_list += basketball_awards_players.columns.values.tolist()#[basketball_awards_players.pos==basketball_awards_players.pos] #pos = position
## year, playerID, lgID

total_list += basketball_coaches.columns.values.tolist()#[basketball_coaches.stint > 2] #stint = time served
## tmID, lgID, year, coachID

total_list += basketball_draft.columns.values.tolist() # draftFrom
## lastName, firstName, tmID, playerID, lgID

total_list += basketball_hof.columns.values.tolist() # hofId = hall of fame
## hofID, name

total_list += basketball_master.columns.values.tolist() #bioID = nameId, height, weight, race
## bioID, firstName, LastName, birthDate

total_list += basketball_player_allstar.columns.values.tolist()# fg = fieldgoal, o_rebound = offensive rebound = rebound when on offense
## player_id, last_name, first_name, league_ID

total_list += basketball_players.columns.values.tolist() #gp = games played
## playerID, lgID, tmID, year

total_list += basketball_series_post.columns.values.tolist()
## tmIDWinner, lgIDWinner, tmIDLoser, lgIDLoser

total_list += basketball_teams.columns.values.tolist()#[basketball_teams.pace>0].columns 
## ' year', 'lgID', 'tmID', 'franchID', 'confID', 'divID'

total_list += nbaallelo.columns.values.tolist()
## 'gameorder', 'game_id', 'lg_id', 'year_id', 'team_id', 'fran_id'

total_list += ncaa_team_data.columns.values.tolist()
## school, coaches, year

total_list += Players.columns.values.tolist()
## Player (Name, lastname), born (birthday), college, height, weight, birth_city+state

total_list += Seasons_Stats.columns.values.tolist()
##'Year', 'Player', 'Pos', 'Age', 'Tm',

In [9]:
# """Find similar columns, with different names.

# """
# first_second = []
# second_first = []

# first_second_notequal = []
# second_first_notequal = []

# for first_item in all_columns:
#     for second_item in all_columns:
#         if first_item in second_item:
#             if first_item == second_item:
#                 first_second += [(first_item, second_item)]
#             else:
#                 first_second_notequal += [(first_item, second_item)]
            
#         if second_item in first_item:
#             if first_item == second_item:
#                 second_first += [(second_item, first_item)]
#             else:
#                 second_first_notequal += [(second_item, first_item)]
                
            
# first_second = list(set(first_second))
# second_first = list(set(second_first))

# first_second_notequal = list(set(first_second_notequal))
# second_first_notequal = list(set(second_first_notequal))

In [5]:
# first_second_notequal, len(first_second_notequal)
#'ft', 'ft_made';'fga', 'd_fga';'name', 'lastname';'pf', 'postpf';'fta', 'd_fta';'l', 'blk%';'g', 'ap_high';
#'g', 'league_id';'l', 'elo_n';'tmid', 'bbtmid';'g', 'height';'fta', 'o_fta';'w', 'post_wins';'l', 'games_played';
#'l', 'neutloss';'year', 'draftyear';'ws', 'ows';'name', 'namenick';'g', 'college';'tmid', 'tmidwinner';
#'college', 'collegeother';'ast', 'forecast';'per', 'personal_fouls';'2p', '2pa'; 'pos', 'postblocks'; 'ft', 'fta'; 
#'rebounds', 'd_rebounds'; 'fga', 'o_fga'; 'name', 'first_name'; '3pa', 'o_3pa'
#'fgattempted', 'postfgattempted'; 'fg', 'fgmade'; '3pa', '3par'; 'pos', 'postthreemade'; 'min', 'postminutes'; 'w', 'win_equiv'
#'ftmade', 'postftmade'; 'age', 'collage'; 'lgid', 'lgidwinner'; 'rebounds', 'postorebounds'; 'ft', 'ftattempted'; 'tm', 'tmidwinner'
#'lost', 'awaylost'; 'fga', 'fgattempted';'name', 'namesuffix'; 'player', 'player_id'; 'school', 'highschool'; 'minutes', 'postminutes'
# 'fg', 'fg_made'; 'fta', 'postftattempted'; 'ft', 'draftoverall'; 'won', 'neutwon'; 'name', 'last_name'
#
#
#

In [6]:
# import math

# all_files = [basketball_abbrev,
# basketball_awards_coaches,
# basketball_awards_players,
# basketball_coaches,
# basketball_draft,
# basketball_hof,
# basketball_master,
# basketball_player_allstar,
# basketball_players,
# basketball_series_post,
# basketball_teams,
# nbaallelo,
# ncaa_team_data,
# Players,
# Seasons_Stats]

# all_file_names = ['basketball_abbrev',
# 'basketball_awards_coaches',
# 'basketball_awards_players',
# 'basketball_coaches',
# 'basketball_draft',
# 'basketball_hof',
# 'basketball_master',
# 'basketball_player_allstar',
# 'basketball_players',
# 'basketball_series_post',
# 'basketball_teams',
# 'nbaallelo',
# 'ncaa_team_data',
# 'Players',
# 'Seasons_Stats']

# def check_content(file, name):
#     player_data = {}
#     alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#     for player, i in zip(file.playerID, range(len(file.playerID))):
#         for col in file[file.playerID == player]:
#             for item in file[file.playerID == player][col]:
#                 for team in file[file.playerID == player].tmID:
#                     if item == item and not col == 'playerID': # is not NaN
#                         item_str = ''

#                         if isinstance(item, int):
#                             item = str(item)
#                             for let in item:
#                                 item_str += alphabet[int(let)]
#                             item = item_str

#                         player_data.setdefault('RowId #', []).append('Row ' + str(i))
#                         player_data.setdefault('PlayerId', []).append(player) #Sentence
#                         player_data.setdefault('Value', []).append(item) #Word
#                         player_data.setdefault('Property', []).append(col) #POS
#                         player_data.setdefault('Team', []).append(team)  #Tag
                        
#     player_data = pd.DataFrame(player_data)
#     player_data.to_csv('results/'+name+'.csv', ';', encoding='utf-8')       
#     return pd.DataFrame(player_data)

# for file, name in zip(all_files, all_file_names):
#     player_data = check_content(file, name)

In [608]:
# nbaallelo

In [7]:
### basketball_abbrev.columns.tolist(),
### basketball_awards_coaches.columns.tolist(),


# basketball_awards_players.columns.tolist(),
# basketball_coaches.columns.tolist(),
# basketball_draft.columns.tolist(),
# basketball_hof.columns.tolist(),
# basketball_master.columns.tolist(),
# basketball_player_allstar.columns.tolist(),
# basketball_players.columns.tolist(),
# basketball_series_post.columns.tolist(),
# basketball_teams.columns.tolist(),
# nbaallelo.columns.tolist(),
# ncaa_team_data.columns.tolist(),
# Players.columns.tolist(),
# Seasons_Stats.columns.tolist(), 

#changing variables:
# height, weight, team, coaches, playoff, win, lost, lgID, minutes, steals, assists, turnovers, blocks, games_played

In [8]:
# all_infile = {}

# for column, columnname in zip(column_list[2:], all_file_names[2:]): # all columns, separated by files
#     store_temp = ''
    
#     for item in list(set(total_list)): # all columns    
#         for col in column: # all columns in 1 file
#             inside = 0
#             if col.lower() in item.lower() and len(col)>1:
#                 print(col, item)
#                 store_temp += '1,'
# #                 all_infile.setdefault(item, []).append(store_temp)
#                 inside = 1
#                 break
        
#         if not inside:
#             store_temp += '0,'
# #             all_infile.setdefault(item, []).append(store_temp)
#     store_temp += '\n'
#     all_infile.setdefault(columnames, []).append(store_temp)
#     break

In [9]:
# len(all_infile), all_infile

In [10]:
# for file in column_list[:1][0]:
#     print(file)

In [363]:
# list(set(total_list))

In [10]:
# column_list

In [11]:
# # basketball_players_in_multiplefile
# bpinmf = []
# for u in basketball_awards_players.playerID: # Award details
#     for v in basketball_draft.playerID: #Draf details
#         if str(u).lower() == str(v).lower() :
#             for w in basketball_player_allstar.playerID: # Game data
#                 if str(u).lower()  == str(w).lower() :
#                     for x in basketball_players.playerID: # Game data
#                         if str(u).lower()  == str(x).lower() :
#                             for y in basketball_master.playerID: # Physical data
#                                 if str(y).lower()  == str(x).lower() :
#                                     bpinmf += [(u, v, w, x, y)]
#                                     break
#                             break
#                     break
#             break

In [12]:
# basketball_master

In [13]:
# one = pd.merge(basketball_awards_players, basketball_draft, on='playerID')
# two = pd.merge(one,  basketball_player_allstar, on='playerID')
# three = pd.merge(two,  basketball_players, on='playerID')
# four = pd.merge(three,  basketball_master, on='playerID')

In [14]:
# from scipy import spatial

In [15]:
# basketball_master = basketball_master.rename(columns={'bioID':'playerID'}) # rename basketball_player_allstar and basketball_master columnname to match playerID

In [16]:
# one.fillna(0).to_csv('results/bap_bd.csv')
# two.fillna(0).to_csv('results/bap_bd_bpa.csv')
# three.fillna(0).to_csv('results/bap_bd_bpa_bp.csv')
# four.fillna(0).to_csv('results/bap_bd_bpa_bp_bm.csv')

In [548]:
# four[four.playerID == 'olajuha01'][['tmID_y', 'year_x', 'tmID_x']]

In [17]:
# len(list(set(two['playerID'])))

In [18]:
# four[four.playerID == 'olajuha01']

In [19]:
# two.columns

In [20]:
# one = pd.merge(basketball_awards_players, basketball_draft, on='playerID')
# two = pd.merge(one,  basketball_player_allstar, on='playerID')
# three = pd.merge(two,  basketball_players, on='playerID')
# four = pd.merge(three, basketball_master, on='playerID')

In [21]:
# len(list(set(pd.merge(basketball_draft, basketball_players, on='playerID')['playerID']))), list(set(pd.merge(basketball_awards_players, basketball_player_allstar, on='playerID')['playerID']))

In [22]:
# len(list(set(pd.merge(basketball_players, basketball_master, on='playerID')['playerID']))) #816

In [39]:
basketball_player_allstar

,player_id,last_name,first_name,season_id,conference,league_id,games_played,minutes,points,o_rebounds,...,steals,blocks,turnovers,personal_fouls,fg_attempted,fg_made,ft_attempted,ft_made,three_attempted,three_made
0,abdulka01,Abdul-Jabbar,Kareem,1978,West,NBA,1,28,11.0,NaN,...,NaN,NaN,NaN,NaN,12.0,5.0,2.0,1.0,NaN,NaN
1,abdulka01,Abdul-Jabbar,Kareem,1969,East,NBA,1,18,10.0,NaN,...,NaN,NaN,NaN,NaN,8.0,4.0,2.0,2.0,NaN,NaN
2,abdulka01,Abdul-Jabbar,Kareem,1988,West,NBA,1,13,4.0,NaN,...,NaN,NaN,NaN,NaN,6.0,1.0,2.0,2.0,NaN,NaN
3,abdulka01,Abdul-Jabbar,Kareem,1987,West,NBA,1,14,10.0,NaN,...,NaN,NaN,NaN,NaN,9.0,4.0,2.0,2.0,NaN,NaN
4,abdulka01,Abdul-Jabbar,Kareem,1986,West,NBA,1,27,10.0,NaN,...,NaN,NaN,NaN,NaN,9.0,4.0,2.0,2.0,NaN,NaN
5,abdulka01,Abdul-Jabbar,Kareem,1985,West,NBA,1,32,21.0,NaN,...,NaN,NaN,NaN,NaN,15.0,9.0,4.0,3.0,NaN,NaN
6,abdulka01,Abdul-Jabbar,Kareem,1984,West,NBA,1,23,11.0,NaN,...,NaN,NaN,NaN,NaN,10.0,5.0,2.0,1.0,NaN,NaN
7,abdulka01,Abdul-Jabbar,Kareem,1983,West,NBA,1,37,25.0,NaN,...,NaN,NaN,NaN,NaN,19.0,11.0,4.0,3.0,NaN,NaN
8,abdulka01,Abdul-Jabbar,Kareem,1982,West,NBA,1,32,20.0,NaN,...,NaN,NaN,NaN,NaN,12.0,9.0,3.0,2.0,NaN,NaN
9,abdulka01,Abdul-Jabbar,Kareem,1980,West,NBA,1,23,15.0,NaN,...,NaN,NaN,NaN,NaN,9.0,6.0,3.0,3.0,NaN,NaN
10,abdulka01,Abdul-Jabbar,Kareem,1979,West,NBA,1,30,17.0,NaN,...,NaN,NaN,NaN,NaN,17.0,6.0,6.0,5.0,NaN,NaN
11,abdulka01,Abdul-Jabbar,Kareem,1976,West,NBA,1,23,21.0,NaN,...,NaN,NaN,NaN,NaN,14.0,8.0,6.0,5.0,NaN,NaN
12,abdulka01,Abdul-Jabbar,Kareem,1975,West,NBA,1,36,22.0,NaN,...,NaN,NaN,NaN,NaN,16.0,9.0,4.0,4.0,NaN,NaN
13,abdulka01,Abdul-Jabbar,Kareem,1974,West,NBA,1,19,7.0,NaN,...,NaN,NaN,NaN,NaN,10.0,3.0,2.0,1.0,NaN,NaN
14,abdulka01,Abdul-Jabbar,Kareem,1973,West,NBA,1,23,14.0,NaN,...,NaN,NaN,NaN,NaN,11.0,7.0,0.0,0.0,NaN,NaN
15,abdulka01,Abdul-Jabbar,Kareem,1972,West,NBA,1,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,abdulka01,Abdul-Jabbar,Kareem,1971,West,NBA,1,19,12.0,NaN,...,NaN,NaN,NaN,NaN,10.0,5.0,2.0,2.0,NaN,NaN
17,abdulka01,Abdul-Jabbar,Kareem,1970,West,NBA,1,30,19.0,NaN,...,NaN,NaN,NaN,NaN,16.0,8.0,4.0,3.0,NaN,NaN
18,abdulka01,Abdul-Jabbar,Kareem,1981,West,NBA,1,22,2.0,1.0,...,3.0,2.0,1.0,3.0,10.0,1.0,0.0,0.0,0.0,0.0
19,abdursh01,A-Rahim,Shareef,2001,East,NBA,1,21,9.0,1.0,...,0.0,0.0,0.0,2.0,4.0,4.0,0.0,0.0,1.0,1.0
20,adamsal01,Adams,Alvan,1975,West,NBA,1,11,4.0,NaN,...,NaN,NaN,NaN,NaN,4.0,2.0,0.0,0.0,NaN,NaN
21,adamsmi01,Adams,Michael,1991,East,NBA,1,14,9.0,NaN,...,NaN,NaN,NaN,NaN,8.0,4.0,0.0,0.0,NaN,NaN
22,aguirma01,Aguirre,Mark,1987,West,NBA,1,12,14.0,NaN,...,NaN,NaN,NaN,NaN,10.0,5.0,3.0,3.0,NaN,NaN
23,aguirma01,Aguirre,Mark,1986,West,NBA,1,17,9.0,NaN,...,NaN,NaN,NaN,NaN,6.0,3.0,3.0,2.0,NaN,NaN
24,aguirma01,Aguirre,Mark,1983,West,NBA,1,13,13.0,NaN,...,NaN,NaN,NaN,NaN,8.0,5.0,4.0,3.0,NaN,NaN
25,aingeda01,Ainge,Danny,1987,East,NBA,1,19,12.0,NaN,...,NaN,NaN,NaN,NaN,11.0,4.0,2.0,1.0,NaN,NaN
26,allenra02,Allen,Ray,2001,East,NBA,1,25,15.0,1.0,...,3.0,0.0,1.0,3.0,17.0,6.0,0.0,0.0,10.0,3.0
27,allenra02,Allen,Ray,2000,East,NBA,1,19,15.0,1.0,...,1.0,1.0,1.0,0.0,15.0,7.0,0.0,0.0,7.0,1.0
28,allenra02,Allen,Ray,1999,East,NBA,1,17,14.0,1.0,...,3.0,1.0,3.0,2.0,13.0,4.0,6.0,5.0,6.0,1.0
29,allenra02,Allen,Ray,2003,West,NBA,1,23,16.0,2.0,...,1.0,0.0,3.0,2.0,13.0,6.0,4.0,3.0,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,willibu01,Williams,Buck,1981,East,NBA,1,22,4.0,1.0,...,0.0,2.0,3.0,0.0,7.0,2.0,2.0,0.0,0.0,0.0
1580,willich01,Williams,Charles,1968,East,ABA,1,5,2.0,0.0,...,NaN,NaN,3.0,0.0,2.0,0.0,2.0,2.0,0.0,0.0
1581,willich01,Williams,Charles,1969,East,ABA,1,7,2.0,NaN,...,NaN,NaN,NaN,2.0,5.0,1.0,0.0,0.0,2.0,0.0
1582,willich02,Williams,Chuck,1972,West,ABA,1,16,5.0,0.0,...,0.0,0.0,1.0,2.0,3.0,2.0,3.0,1.0,0.0,0.0
1583,willich02,Williams,Chuck,1975,Denver,ABA,1,22,7.0,NaN,...,NaN,NaN,NaN,2.0,6.0,2.0,5.0,3.0,0.0,0.0
1584,willide01,Williams,Deron,2009,West,NBA,1,28,14.0,0.0,...,4.0,1.0,5.0,4.0,11.0,6.0,0.0,0.0,4.0,2.0
1585,willigu01,Williams,Gus,1982,West,NBA,1,15,6.0,NaN,...,NaN,NaN,NaN,NaN,9.0,3.0,0.0,0.0,NaN,NaN
1586,willigu01,Williams,Gus,1981,West,NBA,1,26,22.0,2.0,...,1.0,0.0,0.0,1.0,19.0,9.0,4.0,4.0,1.0,0.0
1587,willija01,Williams,Jayson,1997,East,NBA,1,19,4.0,3.0,...,0.0,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,0.0
1588,willike01,Willis,Kevin,1991,East,NBA,1,14,8.0,NaN,...,NaN,NaN,NaN,NaN,10.0,4.0,0.0,0.0,NaN,NaN
1589,willima01,Williams,Mo,2008,East,NBA,1,17,12.0,1.0,...,0.0,0.0,2.0,0.0,10.0,5.0,0.0,0.0,5.0,2.0
1590,wintebr01,Winters,Brian,1977,West,NBA,1,14,8.0,NaN,...,NaN,NaN,NaN,NaN,7.0,4.0,0.0,0.0,NaN,NaN
1591,wintebr01,Winters,Brian,1975,West,NBA,1,16,2.0,NaN,...,NaN,NaN,NaN,NaN,5.0,1.0,0.0,0.0,NaN,NaN
1592,wisewi01,Wise,Willie,1971,West,ABA,1,33,15.0,2.0,...,NaN,NaN,2.0,2.0,8.0,5.0,7.0,5.0,0.0,0.0
1593,wisewi01,Wise,Willie,1972,West,ABA,1,37,26.0,2.0,...,0.0,0.0,1.0,3.0,20.0,11.0,4.0,4.0,0.0,0.0
1594,wisewi01,Wise,Willie,1973,West,ABA,1,25,8.0,6.0,...,1.0,1.0,1.0,1.0,12.0,4.0,0.0,0.0,0.0,0.0
1595,worthja01,Worthy,James,1991,West,NBA,1,14,9.0,NaN,...,NaN,NaN,NaN,NaN,7.0,4.0,1.0,1.0,NaN,NaN
1596,worthja01,Worthy,James,1990,West,NBA,1,21,9.0,NaN,...,NaN,NaN,NaN,NaN,11.0,3.0,4.0,3.0,NaN,NaN
1597,worthja01,Worthy,James,1989,West,NBA,1,19,2.0,NaN,...,NaN,NaN,NaN,NaN,11.0,1.0,0.0,0.0,NaN,NaN
1598,worthja01,Worthy,James,1988,West,NBA,1,18,8.0,NaN,...,NaN,NaN,NaN,NaN,7.0,4.0,0.0,0.0,NaN,NaN
1599,worthja01,Worthy,James,1987,West,NBA,1,13,4.0,NaN,...,NaN,NaN,NaN,NaN,8.0,2.0,1.0,0.0,NaN,NaN
1600,worthja01,Worthy,James,1986,West,NBA,1,29,22.0,NaN,...,NaN,NaN,NaN,NaN,14.0,10.0,2.0,2.0,NaN,NaN
1601,worthja01,Worthy,James,1985,West,NBA,1,28,20.0,NaN,...,NaN,NaN,NaN,NaN,19.0,10.0,0.0,0.0,NaN,NaN
1602,yardlge01,Yardley,George,1958,West,NBA,1,17,6.0,NaN,...,NaN,NaN,NaN,NaN,8.0,2.0,2.0,2.0,NaN,NaN
1603,yardlge01,Yardley,George,1957,West,NBA,1,32,19.0,NaN,...,NaN,NaN,NaN,NaN,15.0,8.0,5.0,3.0,NaN,NaN
1604,yardlge01,Yardley,George,1956,West,NBA,1,25,9.0,NaN,...,NaN,NaN,NaN,NaN,10.0,4.0,1.0,1.0,NaN,NaN
1605,yardlge01,Yardley,George,1955,West,NBA,1,19,8.0,NaN,...,NaN,NaN,NaN,NaN,7.0,3.0,3.0,2.0,NaN,NaN
1606,yardlge01,Yardley,George,1954,West,NBA,1,22,11.0,NaN,...,NaN,NaN,NaN,NaN,11.0,4.0,4.0,3.0,NaN,NaN
1607,yardlge01,Yardley,George,1959,East,NBA,1,16,11.0,NaN,...,NaN,NaN,NaN,NaN,9.0,5.0,2.0,1.0,NaN,NaN
1608,zasloma01,Zaslofsky,Max,1951,East,NBA,1,25,1.0,NaN,...,NaN,NaN,NaN,NaN,7.0,3.0,5.0,5.0,NaN,NaN

In [550]:
# pd.merge(salaries, Seasons_Stats, on='player')

In [2]:
# pd.merge(salaries, Seasons_Stats.rename(columns={'Player':'player', 'Year':'season_end'}), on=['player', 'season_end']) #Seasons_Stats.rename(columns={'Player':'player'})

In [568]:
# len(list(set(pd.merge(basketball_awards_players, salaries1978.rename(columns={'player_id':'playerID'}), on='playerID')['playerID'])))

324

In [4]:
# Step 1
# find all the basketball players that have an ID.
basketball_players = pd.read_csv('data/basketball_players.csv', ',')
basketball_players2 = pd.read_csv('data/basketball_players (2).csv', ',')

pb = []
pb += basketball_players.playerID.tolist()
pb += basketball_players2.playerID.tolist()
pb = list(set(pb))

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
#Step 2, see how many players are in the files

count = 0
number_of_files = {}

all_files = [
basketball_awards_players,
basketball_hof,
basketball_master,
basketball_player_allstar,
basketball_players]

# Players,
# Seasons_Stats]

all_file_names = [
'basketball_awards_players',
'basketball_hof',
'basketball_master',
'basketball_player_allstar',
'basketball_players']

# 'Players',
# 'Seasons_Stats']

basketball_hof = basketball_hof.rename(columns={'hofID':'playerID'})
basketball_master = basketball_master.rename(columns={'bioID':'playerID'})
basketball_player_allstar = basketball_player_allstar.rename(columns={'player_id':'playerID'})
basketball_players = basketball_players.rename(columns={'player_id':'playerID'})
# Check how many players are in each file
for player in pb:
    for file, file_name in zip(all_files, all_file_names):  
        
        if player in list(set(file.playerID.tolist())):
            
            if file_name in number_of_files:
                number_of_files[file_name] += 1
            else:
                number_of_files[file_name] = 0

In [7]:
#Step 3 get additional info of remaining players.
basketball_player_details = pd.merge(basketball_players, basketball_master.rename(columns={'bioID':'playerID'}), on='playerID')

# basketball_player_details.columns

In [8]:
#Step 4 see which players has salaries
counter = 1

for p in list(set(basketball_players.playerID.tolist())):
    if p in list(set(salaries1978.player_id)):
        counter += 1

counter

815

In [9]:
# Step 5 add salaries to dataset
player_and_salaries = pd.merge(basketball_player_details, salaries1978.rename(columns={'player_id':'playerID'}), on=['playerID', 'year'])

In [10]:
# Step 6 Only select the basketball players with more than 5 years of playing
# The average career length of an NBA player is 4.8 years.

player_and_careerlength = player_and_salaries.groupby('playerID').filter(lambda x: len(x) >= 6).sort_values(['playerID', 'year'])
player_careerlenght_cols = player_and_careerlength.columns.tolist()

In [47]:
player_and_careerlength.to_csv('results/player_and_careerlength.csv', index=False)

In [43]:
# Step 6 Only select the basketball players with 6 years of playing
# The average career length of an NBA player is 4.8 years.

# player_and_careerlength.groupby(['playerID', 'year']).agg([np.mean]).to_csv('results/player_and_careerlength_groupbyyear.csv')
player_and_careerlength = pd.read_csv('results/player_and_careerlength_groupbyyear.csv')
player_and_careerlength = player_and_careerlength.groupby('playerID').filter(lambda x: len(x) == 6)#.sort_values(['playerID', 'year'])

player_and_careerlength.to_csv('results/careerlength_is6.csv', index=False)

In [42]:
len(list(set(player_and_careerlength.playerID)))

147

In [1030]:
del player_and_careerlength, compared_bp

In [24]:
# Step 5 Check for each player the changes over the years.
counter = 0
compared_bp_with_previous_year = pd.DataFrame(columns=player_careerlenght_cols)
player_careerlength_cols = pd.DataFrame([player_and_careerlength.iloc[0] >= \
                                         player_and_careerlength.iloc[1]]).columns.tolist()
for i, player in player_and_careerlength.iterrows():
    
    if counter == 0: #initialize variables
        year_old = player.year
        player_old = player.playerID
        player_complete = player
    
    compared_bp = pd.DataFrame([np.where(player_complete > player, 'higher', 
                                         (np.where(player_complete >= player, 'equal', 'lower')))],
                               columns = player_careerlength_cols
                              )
    compared_bp['year'] = player.year
    compared_bp['playerID'] = player.playerID
    compared_bp['salary'] = player.truesalary
    compared_bp['tmID'] = player.tmID
    compared_bp_with_previous_year = compared_bp_with_previous_year.append(compared_bp)
    
    if player_old == player.playerID or player_old == '':''
#         print('Old: ', year_old, player.year, player.playerID)
    else:
#         print('\nNews: ', year_old, player.year, player.playerID)
        year_old = 0
        player_old = ''
    year_old = player.year
    player_old = player.playerID
    counter += 1
    
compared_bp_with_previous_year.to_csv('results/compared_bp_with_previous_year.csv', index=False)

In [1027]:
compared_bp_with_previous_year.to_csv('results/compared_bp_with_previous_year.csv', index=False)

In [1028]:
del compared_bp_with_previous_year

In [803]:
# # Step 3
# # plt.matshow(basketball_players[['playerID', 'year', 'tmID', 'points']][:10].corr())
# basketball_players[['playerID', 'year', 'tmID', 'points']][:10].corr()

# pd.scatter_matrix(basketball_players[['playerID', 'year', 'tmID', 'points']][:10], aplha=0.3, fighsize=(14,8), diagonal='kde')

In [584]:
one = basketball_players2['playerID'].values.tolist() 
one += basketball_players['playerID'].values.tolist()
len(list(set(one)))

4903

In [1029]:
del one

In [586]:
len(list(set(basketball_players['playerID'].values.tolist())) )

816

In [593]:
for playerr in basketball_players.playerID.tolist():
    if not playerr in basketball_players2.playerID.tolist():
        print('Found one')

In [597]:
count_in = 0
count_out = 0
for playerr in salaries.player.tolist():
    if not playerr in salaries1978.player.tolist():
        count_out += 1
    else:
        count_in += 1
    
count_out, count_in

(492, 11346)